server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localtest?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dyb.springcloud.pojo
  configuration:
    map-underscore-to-camel-case: true
